# Generated by Django 3.2.5 on 2023-05-19 10:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image_1', models.ImageField(upload_to='rename_file')),
                ('image_2', models.ImageField(blank=True, upload_to='rename_file')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50)),
                ('title_2', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='rename_file')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rename_file')),
            ],
        ),
        migrations.CreateModel(
            name='ContactHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='rename_file')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='rename_file')),
                ('icon', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='rename__file')),
                ('joinus_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_type', models.CharField(choices=[('About', 'About'), ('Services', 'Services'), ('Features', 'Features'), ('Why_Choose_Us', 'Why_Choose_Us'), ('Video_Section', 'Video_Section'), ('Price', 'Price')], max_length=100)),
                ('short_title', models.CharField(max_length=100)),
                ('main_title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rename_file')),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rename_file')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('PrivacyPolicy', 'PrivacyPolicy'), ('About', 'About')], max_length=100)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='rename_file')),
                ('desc', models.TextField()),
                ('iframe', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WebSiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rename_file')),
                ('fav_icon', models.ImageField(null=True, upload_to='rename_file')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amounts_INR', models.IntegerField()),
                ('amounts_USD', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('button', models.CharField(max_length=150)),
                ('plan_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='pricing_icon/')),
                ('features', models.ManyToManyField(to='config.PricingFeature')),
            ],
        ),
    ]
