# Generated by Django 3.2.5 on 2023-05-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_staticpage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='image',
        ),
    ]
