# Generated by Django 3.2.5 on 2023-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_features_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_section',
            name='title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
