# Generated by Django 3.2.5 on 2023-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_video_section_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
