# Generated by Django 3.2.5 on 2023-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_footer_footer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_section',
            name='iframe',
            field=models.CharField(max_length=600),
        ),
    ]
