# Generated by Django 3.2.12 on 2023-08-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_send_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
    ]
