# Generated by Django 3.2.12 on 2023-08-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_remove_enquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='whatsapp_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
