# Generated by Django 3.2.12 on 2023-08-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0043_cominfo_country_code'),
        ('config', '0010_footer_whatsapp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cards.cards'),
        ),
    ]
