# Generated by Django 3.2.12 on 2023-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_enquiry_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
