# Generated by Django 3.2.5 on 2023-05-19 10:05

import ckeditor.fields
import config.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=600, null=True)),
                ('instagram', models.CharField(max_length=600, null=True)),
                ('twitter', models.CharField(max_length=600, null=True)),
                ('pinterest', models.CharField(max_length=600, null=True)),
                ('youtube', models.CharField(max_length=600, null=True)),
                ('linkedin', models.CharField(max_length=600, null=True)),
                ('video_link', models.CharField(max_length=600, null=True)),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BooleanField(default=False)),
                ('about_us_cection', models.BooleanField(default=False)),
                ('prodcut_and_service_section', models.BooleanField(default=False)),
                ('payment_option_section', models.BooleanField(default=False)),
                ('gallery_section', models.BooleanField(default=False)),
                ('video_section', models.BooleanField(default=False)),
                ('enquiry_section', models.BooleanField(default=False)),
                ('show_menu', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50, null=True)),
                ('font_color', models.CharField(max_length=50, null=True)),
                ('primary_font', models.CharField(max_length=50, null=True)),
                ('secondry_font', models.CharField(max_length=50, null=True)),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Currency', models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD')], max_length=100)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='rename_file')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOfCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=200)),
                ('amounts_INR', models.IntegerField()),
                ('amounts_USD', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('plan_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='pricing_icon/')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
                ('features', models.ManyToManyField(to='config.PricingFeature')),
                ('pricing_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='rename_file')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='ComInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number_1', models.CharField(max_length=50, null=True)),
                ('contact_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('google_map_link', models.CharField(max_length=600, null=True)),
                ('upload_company_profile', models.ImageField(null=True, upload_to=config.models.rename_file)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Ac_holder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_number', models.IntegerField(blank=True, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('IBAN_number', models.IntegerField(blank=True, null=True)),
                ('SWIFT_code', models.IntegerField(blank=True, null=True)),
                ('type_of_QR', models.CharField(choices=[('GooglePay', 'GooglePay'), ('Paytm', 'Paytm'), ('Phonepe', 'Phonepe'), ('Other', 'Other')], max_length=50, null=True)),
                ('uplaod_QR_image', models.ImageField(blank=True, null=True, upload_to='rename_file')),
                ('payment_number', models.IntegerField(blank=True, null=True)),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estblishment_year', models.DateField(blank=True)),
                ('GSTIN_No', models.CharField(blank=True, max_length=20)),
                ('upload_documents', models.FileField(blank=True, upload_to='documents')),
                ('Desc', ckeditor.fields.RichTextField(blank=True)),
                ('business_nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.businessnature')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
            ],
        ),
    ]
