# Generated by Django 3.2.5 on 2023-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_auto_20230523_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
