# Generated by Django 3.2.5 on 2023-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0003_alter_cominfo_google_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='show_menu',
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='enquiry_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gallery_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='payment_option_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='prodcut_and_service_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='video_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='view_count',
            field=models.BooleanField(default=True),
        ),
    ]
