# Generated by Django 3.2.5 on 2023-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_auto_20230526_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='upload_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
