# Generated by Django 3.2.5 on 2023-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0008_rename_company_profile_cominfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='upload_documents',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents'),
        ),
    ]
