# Generated by Django 3.2.5 on 2023-05-26 06:08

import Cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0013_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='logo',
            field=models.ImageField(null=True, upload_to=Cards.models.rename_file),
        ),
        migrations.AlterField(
            model_name='cominfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=Cards.models.rename_file),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to=Cards.models.rename_file),
        ),
    ]
