# Generated by Django 3.2.5 on 2023-05-26 06:42

import Cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0015_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to=Cards.models.rename_file),
        ),
    ]
