# Generated by Django 3.2.5 on 2023-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0016_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
