# Generated by Django 3.2.5 on 2023-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0017_cards_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
