# Generated by Django 3.2.5 on 2023-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0018_alter_cards_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
