# Generated by Django 3.2.5 on 2023-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0019_cards_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
