# Generated by Django 3.2.5 on 2023-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0020_cards_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
