# Generated by Django 3.2.5 on 2023-06-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_video_section_iframe'),
        ('Cards', '0021_cards_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='stripe_payment_intent',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=200)),
                ('is_payment', models.BooleanField(default=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cards.cards')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.pricing')),
            ],
        ),
    ]
