# Generated by Django 3.2.5 on 2023-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0022_auto_20230605_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=200, null=True),
        ),
    ]
