# Generated by Django 3.2.5 on 2023-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0023_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
