# Generated by Django 3.2.5 on 2023-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0025_cards_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='is_expire',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
