# Generated by Django 3.2.5 on 2023-06-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_video_section_iframe'),
        ('Cards', '0028_remove_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='features',
            field=models.ManyToManyField(null=True, to='config.PricingFeature'),
        ),
        migrations.AddField(
            model_name='orders',
            name='validity',
            field=models.IntegerField(null=True),
        ),
    ]
