# Generated by Django 3.2.12 on 2023-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0029_auto_20230608_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='Account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='type_of_QR',
            field=models.CharField(blank=True, choices=[('GooglePay', 'GooglePay'), ('Paytm', 'Paytm'), ('Phonepe', 'Phonepe'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
