# Generated by Django 3.2.12 on 2023-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0030_auto_20230811_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='IBAN_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='SWIFT_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='payment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
