# Generated by Django 3.2.12 on 2023-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0032_alter_bankdetail_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='Account_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
