# Generated by Django 3.2.12 on 2023-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0033_alter_bankdetail_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
