# Generated by Django 3.2.12 on 2023-08-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0036_cards_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cominfo',
            name='company_name',
        ),
    ]
