# Generated by Django 3.2.12 on 2023-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0037_remove_cominfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cominfo',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
