# Generated by Django 3.2.12 on 2023-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0038_cominfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='active_deactive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
