# Generated by Django 3.2.12 on 2023-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0039_cards_active_deactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='active_deactive',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
