# Generated by Django 3.2.12 on 2023-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0040_alter_cards_active_deactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
