# Generated by Django 3.2.12 on 2023-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0042_alter_cominfo_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cominfo',
            name='country_code',
            field=models.CharField(default='91', max_length=50, null=True),
        ),
    ]
