# Generated by Django 3.2.12 on 2023-08-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0043_cominfo_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cominfo',
            name='country_code',
        ),
    ]
