# Generated by Django 3.2.12 on 2023-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0044_remove_cominfo_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='estblishment_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
